steps:
  - uses: actions/checkout@v4
  - name: Use Node.js
    uses: actions/setup-node@v4
    with:
      node-version: "22"
      cache: "npm"

  - run: npm install

  - name: Run Tests with Coverage
    # Tämä luo coverage/lcov.info tiedoston, jota Coveralls etsii
    run: node --experimental-vm-modules node_modules/jest/bin/jest.js --coverage

  - name: Coveralls GitHub Action
    uses: coverallsapp/github-action@v2
    with:
      # TÄRKEÄ: Tämä rivi riittää tunnistautumiseen
      github-token: ${{ secrets.GITHUB_TOKEN }}
